// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuhnuobpvwmxzsgaqydq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51aG51b2JwdndteHpzZ2FxeWRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODM4ODEsImV4cCI6MjA2NzU1OTg4MX0.fxoZ6VaFv67zifnDfnIi9hUA0n3mTH18XGsoeoGmEaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});